---
- import_tasks: centos_prerequisites.yml
  when: ansible_distribution == "CentOS"

- name: install git
  become: true
  package:
    name: git

- name: install graphical git tools
  when: git_graphical_tools
  become: true
  package:
    name:
      - git-gui
      - gitk

- name: "set user global push strategy to '{{ git_push_strategy }}'"
  git_config:
    scope: global
    name: "push.default"
    value: "{{ git_push_strategy }}"

- name: "set user global pull --rebase strategy to '{{ git_pull_rebase | string | lower }}'"
  git_config:
    scope: global
    name: "pull.rebase"
    value: "{{ git_pull_rebase | string | lower }}"

- name: "set user global rebase autosquash to '{{ git_rebase_autosquash | string | lower }}'"
  git_config:
    scope: global
    name: "rebase.autosquash"
    value: "{{ git_rebase_autosquash | string | lower }}"

- name: "set user global branch autosetuprebase to '{{ git_branch_autosetuprebase }}'"
  git_config:
    scope: global
    name: "branch.autosetuprebase"
    value: "{{ git_branch_autosetuprebase }}"

- import_tasks: user.yml
  when: git_user_name != ""

- import_tasks: aliases.yml
  when: git_aliases

- import_tasks: archivestotext.yml
  when: git_archivestotext
- import_tasks: docxtotext.yml
  when: git_docxtotext
- import_tasks: pdftotext.yml
  when: git_pdftotext
- import_tasks: xlsxtotext.yml
  when: git_xlsxtotext

- import_tasks: rerere.yml
  when: git_rerere

- import_tasks: editor_nano.yml
  when: git_editor_nano

- import_tasks: prompt.yml
  when: git_prompt
