---
- import_tasks: tasks/centos_prerequisites.yml
  when: ansible_distribution == "CentOS"

- name: install git
  become: yes
  package:
    name: git

- name: install graphical git tools
  when: git_graphical_tools
  become: yes
  package:
    name:
    - git-gui
    - gitk

- name: "set user global push strategy to '{{ git_push_strategy }}'"
  git_config:
    scope: global
    name: "push.default"
    value: "{{ git_push_strategy }}"

- name: "set user global pull --rebase strategy to '{{ git_pull_rebase | string | lower }}'"
  git_config:
    scope: global
    name: "pull.rebase"
    value: "{{ git_pull_rebase | string | lower }}"

- import_tasks: tasks/user.yml
  when: git_user_name != ""

- import_tasks: tasks/aliases.yml
  when: git_aliases

- import_tasks: tasks/archivestotext.yml
  when: git_archivestotext
- import_tasks: tasks/docxtotext.yml
  when: git_docxtotext
- import_tasks: tasks/pdftotext.yml
  when: git_pdftotext
- import_tasks: tasks/xlsxtotext.yml
  when: git_xlsxtotext

- import_tasks: tasks/rerere.yml
  when: git_rerere

- import_tasks: tasks/editor_nano.yml
  when: git_editor_nano

- import_tasks: tasks/prompt.yml
  when: git_prompt
