#! /bin/bash

if [ $# -ne 1 ]; then
  echo "Invalid number of arguments. Expecting a single commit hash!"
else
  FIXUP_COMMIT="$1"
  FIXUP_COMMIT_MESSAGE=$(git log --format=%B -1 $FIXUP_COMMIT)
  echo "Fixing up commit \"$FIXUP_COMMIT_MESSAGE\" ($FIXUP_COMMIT) with current staged changes"

  git commit --fixup "$FIXUP_COMMIT" && \
    GIT_SEQUENCE_EDITOR=: git rebase --interactive --autostash --autosquash "$FIXUP_COMMIT"~1
fi
