name: ansible_run

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-bionic
          - ubuntu-focal

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: System information
        run: |
          uname -a
          lsb_release -a
          sudo docker --version

      - name: Prepare and run container
        run: |
          sudo ./testing/1_create.sh ${{matrix.distro}}

      - name: Test ansible
        run: |
          sudo docker exec test-container /etc/ansible/roles/git-tools/testing/3_test.sh --idempotence
